sudo: false
language: node_js
node_js:
- '4.2'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
after_success:
- npm run deploy
env:
  global:
    secure: ZNheiaoMnFWCHudSGik8Z0qX9fVhMprPmU86fktxe6SxyDv5jJBJ+rRToY5jEzk/d39TxTgJ1ycQKxAPbjAqjrhZyD+afsSwipdd5mZFonjAEyJseuZbOCjG2IMYwyWba4qvkrnP0Qxlkv12B+mNdYrjDfVhAVMQbaiDKAq6vFLl2Lqqs3dclvKAem/crdufzcf4EaOkpm9Lu7hVoSnaRFn48VXe6zitGxmdpmrD5jea+DnyKkeUfu4Ys4btGx3uugHWnFVGs81FHIg7Be12BQsKxXQF5nYrJwbw1fOd9vCGF4BbLGdvIEKv/5DJeFhjNCwklGF8yU0UElD46JeispuREGbg7iR2h4FpxPnvXU2WDGlu1OQLRWc0L8L1psxh2v13Lz/SDwDVGRu8ikCG/Kwga2ejC9JWtNJw+lmZZ+Sctz1Wpk60oPkeQfILPZ8PwNU7FqbdblE5S/gmQenEHHDkHyuyvXZBwT69texSz67A5J5svVoOcYDGMHECMq7W8ievSq35hjtnxt4fAH4Iet49PgqM/QhmJgQ1w2FkCKlxyxcUVumer+R1qaRI7cc0rKiFpJVgUxWnF2N6TWRB7gFkpOfIKDw5MDLDTiwaWX2Qg4l/Ym9XeG/NC9OoT5xxAQqkRAH41kOt+BSMoAJhVa3DlTGvE/2osDc/s9TeVvc=
